### ISSUE TITLE
build repo readme should show/tell end result of compile.sh 

### ISSUE THREAD

**Issue by ForestJohnson** [armbian/documentation#102]
https://github.com/armbian/build/blob/master/README.md

How about changing the "How to build an image or a kernel?" section, where it says:

```text
apt-get -y install git
git clone https://github.com/armbian/build
cd build
./compile.sh
```

Maybe we should add something like 

when you run ./compile.sh it will:
  * ask the user what they want to build
  * ensure the current environment is suitable to building
  * download tons of source repositories
  * compile the u-boot, kernel, drivers, etc
  * put the root file system together
  * finally, spit out a disk image file to `location/filename`

**Comment by EvilOlaf** [comment]
I do not think this is necessary? The headline implies that these commands are necessary to get either a kernel package or an image. Also the alternating pictures show that the script will guide the user through the process.

**Comment by EvilOlaf** [comment]
Fixed by https://github.com/armbian/build/commit/a329744e3067dce0b26c9f3abde6e151e9e39714
