### ISSUE TITLE
Build Process page not linked?

### ISSUE THREAD

**Issue by TRSx80** [armbian/documentation#109]
Just going through on consistency pass, I came across this.

The file `Developer-Guide_Build-Process.md` is not linked in the menu in `mkdocs.yml`?

Is this an oversight, or was it removed on purpose?

**Comment by EvilOlaf** [comment]
Some pages were disabled because there were no (longer) needed. Outdated, redundant information, whatever reason.

**Comment by TRSx80** [comment]
OK, thanks for clarification Werner.

Since I was already going through it all anyway, I made a list.  Here are all the currently un-linked files, as of now (including the file from OP):
```
Developer-Guide_Build-Process.md
Developer-Guide_Testing-Procedures.md
Process_Armbian-Task-Tracking.md
User-Guide_Getting-Started-Download-Page.md
User-Guide_Migration_from_Bananian.md
```
