### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by PanderMusubi** [armbian/documentation#113]
Several broken links can be found with [this validator](https://validator.w3.org/checklink?uri=https%3A%2F%2Fdocs.armbian.com&hide_type=all&recursive=on&depth=&check=Check) and need fixing.

While this is being fixed, also the main website has [some](https://validator.w3.org/checklink?uri=https%3A%2F%2Farmbian.com&hide_type=all&recursive=on&depth=&check=Check) that need attention.

**Comment by EvilOlaf** [comment]
@TRSx80 wanna take on the challenge for the docs?
@lanefu for the main website?

**Comment by TRSx80** [comment]
I can probably have a look today.

But first, coffee.  :coffee:        :smile:

**Comment by EvilOlaf** [comment]
Fixed in #114 and a few more.
Some links are still marked as defect but they are either 3rd party, false positive or do not need any action.
