### ISSUE TITLE
Document how to use armbian_first_run.txt

### ISSUE THREAD

**Issue by lanefu** [armbian/documentation#116]
Great for reconfiguring wifi, static network etc.  nothing in docs

**Comment by EvilOlaf** [comment]
Isn't there an example file somewhere anyways?

**Comment by igorpecovnik** [comment]
No idea - i never used this. Its a community addition.

**Comment by lanefu** [comment]
here's how I do it from customize_image.sh

but user could mount image and do the same

```
cat > /boot/armbian_first_run.txt << EOL
FR_net_change_defaults=1

# Enable WiFi or Ethernet.
#       NB: If both are enabled, WiFi will take priority and Ethernet will be disabled.

FR_net_ethernet_enabled=1
FR_net_wifi_enabled=1

#Enter your WiFi creds
#       SECURITY WARN: Your wifi keys will be stored in plaintext, no encryption.

FR_net_wifi_ssid='MY_NETWORK'
FR_net_wifi_key='MY_NETWWORK_PASSWORD'

#       Country code to enable power ratings and channels for your country. eg: GB US DE | https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

FR_net_wifi_countrycode='US'

EOL

}
```

**Comment by EvilOlaf** [comment]
Is this still up to date? There is customization to configure this and .not_logged_in_yet also can be fed with this stuff.

**Comment by igorpecovnik** [comment]
> There is customization to configure this and .not_logged_in_yet also can be fed with this stuff.

> Is this still up to date?

I think mainly yes. I was testing this when changing networking, but we would need to have some bits in docu.

https://github.com/armbian/build/pull/6194
