### ISSUE TITLE
Document Common use cases for using specific functions

### ISSUE THREAD

**Issue by lanefu** [armbian/documentation#121]
Extend this https://docs.armbian.com/Developer-Guide_Build-Preparation/#executing-any-bash-statement

to document common use cases for testing such as

* building bsp packages only
* building Armbian-config only
* checking out source and patching only

**Comment by EvilOlaf** [comment]
Also explain that this is nothing where users can input values and the build system does whatever they are asking for. Directly at least.

**Comment by EvilOlaf** [comment]
Docs for new commands (kernel, kernel-patch, kernel-config ...) is wip
