### ISSUE TITLE
To add usb dongle to tested 3rd party hardware

### ISSUE THREAD

**Issue by PanderMusubi** [armbian/documentation#128]
Not sure where to report this. Please let me know if this is the proper channel or procedure.

For https://www.armbian.com/pine64/ this USB Ethernet dongle is working properly: https://www.amazon.com/StarTech-com-USB-Gigabit-Ethernet-Adapter/dp/B0095EFXMC/

It appears in the output of `lsusb` as `ID 0b95:1790 ASIX Electronics Corp. AX88179 Gigabit Ethernet`

Small improvement for existing supported 3rd party hardware is that the A1 SD card is called 32 MB but the picture is 16 GB.

**Comment by EvilOlaf** [comment]
The chip is already mentioned?
![grafik](https://user-images.githubusercontent.com/3305006/106999769-0d850780-6787-11eb-8329-0be38e10031a.png)

**Comment by PanderMusubi** [comment]
The chip is indeed ASIX AX88179, source is data sheet from https://www.uk.shi.com/Product/26256925?EventID=fbfdc806-4dae-45aa-a0b6-9571e0aeae02 (which even has a 'work with Linux' sticker)

**Comment by PanderMusubi** [comment]
Small improvement for listing of this device, please change `USB3.0 1000Mbps` into `USB3.0 / 1000Mbps`.

**Comment by EvilOlaf** [comment]
@igorpecovnik do you want to add this hardware to the list or is it only for stuff that you have laying around in the lab?

**Comment by igorpecovnik** [comment]
Nah, its enough that we have one of its kind (chip). I have made that cosmetic change:

"please change USB3.0 1000Mbps into USB3.0 / 1000Mbps."

That's it.
