### ISSUE TITLE
Tested 3rd party hardware USB Ethernet AX88772B

### ISSUE THREAD

**Issue by PanderMusubi** [armbian/documentation#130]
This `USB Ethernet` with chipset `AX88772B` for `USB2.0 / 100Mbps` also works, tested on PINE64 with 5.10.16-sunxi64 21.02.2.

Amazon: https://www.amazon.com/USB-RJ45-LAN-Ethernet-Converter/dp/B0863YJB8W/

Image of device shipped by ASUS which I tested: https://dkstatics-public.digikala.com/digikala-products/114070112.jpg

**Comment by EvilOlaf** [comment]
@igorpecovnik kind a similar to https://github.com/armbian/documentation/issues/128

**Comment by igorpecovnik** [comment]
added
