### ISSUE TITLE
Broken keyserver-link when trying to verify download

### ISSUE THREAD

**Issue by johays** [armbian/documentation#146]
Doku at https://docs.armbian.com/User-Guide_Getting-Started/#how-to-check-download-authenticity states
`gpg --keyserver ha.pool.sks-keyservers.net --recv-key DF00FAF1C577104B50BF1D0093D6889F9F0E78D5`

However, keyservers.net are depreciated, and keyserver ha.pool.sks-keyservers.net is not answering:
`gpg: keyserver receive failed: No name`

Can anybody reproduce this?
(Found the key at some other keyserver, but it gives a bad signature - gonna report this as a separate issue)

_EDIT: asc-file gives a good signature when verified directly to the .img.xz and not the .sha file, forget the last sentence_

**Comment by igorpecovnik** [comment]
Docs should be changed to the method without using keyservers. They are quite unreliable, yes ...
