### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by EvilOlaf** [armbian/documentation#151]
https://forum.armbian.com/topic/18216-support-for-apple-m1/?do=findComment&comment=127388

**Comment by EvilOlaf** [comment]
WIP https://github.com/armbian/documentation/pull/152

**Comment by lanefu** [comment]
merged #152

**Comment by lanefu** [comment]
@EvilOlaf thanks for making this happen!

**Comment by EvilOlaf** [comment]
You're welcome!
