### ISSUE TITLE
I think there was a typo or maybe a spelling

### ISSUE THREAD

**Issue by EmadDeve20** [armbian/documentation#164]
i reading this https://docs.armbian.com/User-Guide_FAQ/ linke and i see a text :  ```tl;dr:```

you can see this [text in ](https://docs.armbian.com/User-Guide_FAQ/#why-is-armbian-constantly-asking-for-money-free-software-should-be-free)

so what is that ?

tl;dr means : ```linus torvalds Doctor?```

**Comment by EmadDeve20** [comment]
i know no what is ```tl;dr:```
i am serious!

**Comment by igorpecovnik** [comment]
Copy and paste into your [best friend](https://www.google.com/).

**Comment by EmadDeve20** [comment]
thank you @igorpecovnik  again 👍🏼

**Comment by igorpecovnik** [comment]
Thank you for being professional and respectful. Not seeing that very often from my customers.
