### ISSUE TITLE
EspressoBin v7 on armbian Bad Linux ARM64 Image magic

### ISSUE THREAD

**Issue by rubenkr** [armbian/documentation#165]
Hi eveyone,

first of all thank you so much for this community. I am using armbian a lot on other SBC. However I found out that lately that armbian is no longer officially supported for EspressoBin. However I wanted to try it instead of throwing the SBC to the trash.

**Device**
- EspressoBin v7 DDR4 1G 1000_800Mhz

**Baseline - What did I do?**
1. Update U-Boot according [https://www.armbian.com/espressobin](url) to devel-18.12.3
2. Flashed SD-Card with armbian Focal via Balena according [https://docs.armbian.com/User-Guide_Getting-Started/](url)
3. Updated Boot Environment according [https://www.armbian.com/espressobin/#kernels-archive-all](url)

**Problem Description**
- U-Boot Loads and starts over to boot from SD-Card
- Booting from SD fails with 
`Marvell>> boot
*** ERROR: `serverip' not set
*** ERROR: `serverip' not set
Bad Linux ARM64 Image magic!
`

I would be very grateful for any hints how to get armbian booted on the EspressoBin in 2022!

Happy Holidays to all. cheers

**Full Logs**

`U-Boot 2018.03-devel-18.12.3-gc9aa92ce70-armbian (Sep 18 2020 - 10:07:21 +0200)

Model: Marvell Armada 3720 Community Board ESPRESSOBin
       CPU     1000 [MHz]
       L2      800 [MHz]
       TClock  200 [MHz]
       DDR     800 [MHz]
DRAM:  1 GiB
Comphy chip #0:
Comphy-0: USB3          5 Gbps    
Comphy-1: PEX0          2.5 Gbps
Comphy-2: SATA0         6 Gbps    
SATA link 0 timeout.
AHCI 0001.0300 32 slots 1 ports 6 Gbps 0x1 impl SATA mode
flags: ncq led only pmp fbss pio slum part sxs 
PCIE-0: Link up
MMC:   sdhci@d0000: 0
Loading Environment from SPI Flash... SF: Detected mx25u3235f with page size 256 Bytes, erase size 64 KiB, total 4 MiB
OK
Model: Marvell Armada 3720 Community Board ESPRESSOBin
Net:   eth0: neta@30000 [PRIME]
`

**Comment by igorpecovnik** [comment]
> However I found out that lately that armbian is no longer officially supported for EspressoBin.

Community support still exists, but not here (this is armbian documentation repository issue tracker), here: https://forum.armbian.com/forum/32-armada-a388-a3700/ There you can find hints and perhaps some people that can help.
