### ISSUE TITLE
Push base deployment to docs server

### ISSUE THREAD

**Issue by lanefu** [armbian/documentation#196]
i've been delaying thing this too long.. werner will be happy...

* create chroot jail on server for upload account

@igorpecovnik did you have a method already for managing ssh keys on get gethub?

my old plan was crypt and shenangins

```
jobs:
  test_secrets_management:
    name: do secrety things
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ci-test
          clean: true
      - name: Do some tests
        shell: bash {0}
        run: |
         eval $(ssh-agent)
         cd ci-test
         TEST_HOST=testhost.example.com
         TEST_USER=rsync_user
         SSH_KEYFILE="secrets/test_ssh_key.cpt"
         ssh-add <(ccat $PWD/${SSH_KEYFILE} -K ${{secrets.keyword}})
         echo "Unique Data $(uuidgen)" > testfile
         rsync -auv testfile ${TEST_USER}@${TEST_HOST}:

```

**Comment by EvilOlaf** [comment]
\o/

Method of grabbing has been changed slightly due to latest pushes. Now it is to grab the latest release instead of latest artifact.

**Comment by igorpecovnik** [comment]
> did you have a method already for managing ssh keys on get gethub?

Yes I do. Build artefacts are uploading to NAS in the process. You would want to upload documentation (pdf) somewhere?
