### ISSUE TITLE
combine boards and cross reference?

### ISSUE THREAD

**Issue by EvilOlaf** [armbian/documentation#202]
Mostly a question for @TRSx80: Why there are two tables instead of simply adding a column and merge? Is there a special reason?

**Comment by TRSx80** [comment]
Database normalization.

In other words, combining to one table would result in needing to change the same data on many lines.  Compared to how it is now, with the (name/handle cross reference) data in only one (separate) place.

Current representation can be seen as two (database) tables, a boards table and a name lookup table.

**Comment by EvilOlaf** [comment]
I don't know why that would make a big difference but welp, you  maintain it anyways :D
