### ISSUE TITLE
clockworkpi is imprecisly

### ISSUE THREAD

**Issue by EvilOlaf** [armbian/documentation#205]
They have multiple products. Which one is actually maintained? 
@littlecxm

**Comment by EvilOlaf** [comment]
Ah okay. Perhaps board config an tag should be `clockworkpi-a06` then?

**Comment by littlecxm** [comment]
> Ah okay. Perhaps board config and tag should be `clockworkpi-a06` then?

yeah should be nice

**Comment by EvilOlaf** [comment]
https://github.com/armbian/documentation/commit/896b3cf6037ff648b7e0bb9db6d752bd1347ce14
