### ISSUE TITLE
PDF documentation link is not found

### ISSUE THREAD

**Issue by peter279k** [armbian/documentation#213]
In the [README.md](https://github.com/armbian/documentation/blob/master/README.md), it mentions that it has the PDF document in the Overview section. However, the [PDF document](https://github.com/armbian/documentation/raw/master/document.pdf) link is not found. I think this line should be removed because it seems that the PDF document file is not available anymore.

**Comment by EvilOlaf** [comment]
Up-to-date offline documentation as pdf is always within releases: https://github.com/armbian/documentation/releases
Link needs adjustment

**Comment by EvilOlaf** [comment]
Can be merge once another member put their fingers on ;)

Thanks for the hint.
