### ISSUE TITLE
[ReadMe.md]:Build parameters... is a blink link

### ISSUE THREAD

**Issue by bruce-the-terrible** [armbian/documentation#219]
[Build parameters, advanced build options, user defined configuration, build with Docker?](https://github.com/bruce-the-terrible/armbian#additional-information)    is a blind link.
click on this link means nothing

帮助文件里面有一个死链接，点不开

**Comment by EvilOlaf** [comment]
Cannot find. Please send permalink to broken link.

**Comment by bruce-the-terrible** [comment]
sorry,the link is below

https://github.com/armbian/build#additional-information

**Comment by EvilOlaf** [comment]
Ahaa. Issue is in the build repository, not in documentation. Therefore could not find it. 
Next time please report issue in the repository that is affected.
Fix pending: https://github.com/armbian/build/pull/3853
Thanks.
