### ISSUE TITLE
Provide a nmcli alternative to create AP

### ISSUE THREAD

**Issue by lampra1** [armbian/documentation#231]
I found this handy, so this could be added to the documentation:
Use
`nmcli device show` 
to get the name of the wifi (eg `wlx48022a5`)
Then create the access point.
`nmcli dev wifi hotspot ifname wlx48022a5 ssid Armbian password "12345678"`

PS: I do not know, nor I can test at the moment if this survives reboot

**Comment by EvilOlaf** [comment]
I think this is probably a bit out of scope of documentation. However here would be a nice place: https://forum.armbian.com/forum/40-reviews-tutorials-hardware-hacks/

**Comment by lampra1** [comment]
There is already such documentation [here](https://github.com/armbian/documentation/blob/master/docs/User-Guide_Advanced-Features.md#how-to-set-wireless-access-point)
