### ISSUE TITLE
device support search results vs 404

### ISSUE THREAD

**Issue by CouldBeThis** [armbian/documentation#244]
Search for a device in the [download page](https://www.armbian.com/download/). Type a keyword then press "Search".  There are only 2 possible results that I can obtain:

1. Search for a device that dose exist, like [pine64](https://www.armbian.com/download/?s=pine64) and every device is shown no matter which ones contain the search term

![image](https://user-images.githubusercontent.com/53547181/180598475-b86d3a28-69fb-450b-9a9c-5b5a7d3a49bc.png)

[page continues on down the list]

2. search for a term that is probably not found in the devices, like [ladeeda](https://www.armbian.com/download/?s=nonesense), and you get a 404 

![image](https://user-images.githubusercontent.com/53547181/180598413-e96fd9b3-e669-46ec-8b8f-a7d55f989986.png)

hope this is the right repo; not certain. I apologize if wrong one. 

Issue edited Jul 31 22 to narrow scope. @EvilOlaf points out that there is a pop up under the search box. This issue only occurs when using the "Search" button. Expected behaviour for "Search" button is updated results on the page itself. In situations where results are only available via popup, generally "Search" button is not present. What is the function of the "Search" button here?

**Comment by EvilOlaf** [comment]
![grafik](https://user-images.githubusercontent.com/3305006/180715981-4727b404-497c-4e41-b760-d2cd625e57fc.png)

![grafik](https://user-images.githubusercontent.com/3305006/180716030-a44df7b8-191f-4127-b10a-3dde23bff93a.png)


Works for me

**Comment by igorpecovnik** [comment]
Still strange why search doesn't work. Can't recall if this was working in 1st place.

**Comment by CouldBeThis** [comment]
@EvilOlaf you are correct it works for the popup search. I am old fashioned and I always press the actual "Search" button which I expect to load the results on the page. I will modify the issue to include that step.

**Comment by igorpecovnik** [comment]
we disabled this so not relevant anymore.
