### ISSUE TITLE
Broken "Edit on Github" button

### ISSUE THREAD

**Issue by CornyjK** [armbian/documentation#31]
"Edit on Github" button redirects me [here](https://github.com/lanefu/armbianDocsAndProcess/edit/master/docs/index.md) - target does not exist, probably old repo URL.

**Comment by jcstaudt** [comment]
Just FYI, the **Edit on GitHub** link takes me to ``https://github.com/armbian/documentation/edit/master/docs/index.md`` which notifies all non-contributors that **You need to fork this repository to propose changes.**

The full path of the intended landing page is ``https://github.com/armbian/documentation/blob/master/docs/index.md``

**Comment by igorpecovnik** [comment]
It should work properly from here: https://docs.armbian.com and it looks it does.
