### ISSUE TITLE
Logo not shown in certain page

### ISSUE THREAD

**Issue by PanderMusubi** [armbian/documentation#320]
On https://docs.armbian.com/Process_Documentation/ I think the logo should be shown but only the text `logo` is shown.

![Screenshot from 2023-03-27 22-10-50](https://user-images.githubusercontent.com/198964/228055223-302da873-402b-4c93-a590-46ebf85bd4b2.png)

**Comment by EvilOlaf** [comment]
Hm interesting. This page is more or less just a redirect to `README.md` in repository root. Viewed from there the path to the logo file is correct while when having docs compiled it does not know about the  `docs` subfolder anymore and therefore breaks the link...

**Comment by igorpecovnik** [comment]
This part was removed from docs. closing.
