### ISSUE TITLE
Outdated documentation MAC address pine64

### ISSUE THREAD

**Issue by PanderMusubi** [armbian/documentation#321]
The text in the line https://github.com/armbian/documentation/blame/master/docs/board_details/pine64.md#L6 is outdated. The file `/boot/uEnv.txt` is no longer used. Setting `ethaddr` in there, using all the information from https://docs.armbian.com/User-Guide_Basic-Troubleshooting/#mac-address-conflicts or runninng `nmtui` does not result in setting a MAC address.

Is the MAC address randomly set each time? If not, where is it stored? I cannot find the MAC address anywhere, however, rebooting results always in the same MAC address. Perhaps the random process is random for the board but is persistent in providing the same address?

**Comment by EvilOlaf** [comment]
file has been removed
