### ISSUE TITLE
OLIMEX Teres-A64: No known limitations -> Update product page

### ISSUE THREAD

**Issue by Kreyren** [armbian/documentation#323]
The website https://www.armbian.com/olimex-teres-a64 presents:

![teres-no-limits](https://user-images.githubusercontent.com/11302521/228518870-1415026d-c576-4d09-bc22-f977210212c8.png)

Which are outdated:
* **suspend/resume** works without any known issues thanks to the use of crust, which is documented in the u-boot docs https://u-boot.readthedocs.io/en/latest/board/allwinner/sunxi.html#building-the-crust-management-processor-firmware
* **brightness level** can be adjusted through fn keys without any known issues
* **Audio was tested and works without any known issues**, but https://wiki.debian.org/InstallingDebianOn/Olimex/Teres-I#Audio should be linked as post-installation configuration might be needed in some scenarios due to debian's and ubuntu's weird handling of `pipewire` at the current testing release requiring to set the `Pro Audio`device output. (i tried to implement this fix in board-specific configuration, but debian changes things too often there so it's not reliable fix atm)

CC @igorpecovnik

**Comment by igorpecovnik** [comment]
send you pwd so you can edit those items directly.
