### ISSUE TITLE
Improved link for PINE64 to documentation

### ISSUE THREAD

**Issue by PanderMusubi** [armbian/documentation#324]
On https://www.armbian.com/pine64/ there is a link under Documentation that goes to https://docs.armbian.com/ but it is better if that link goes to so that users directly land on the PINE64 specific documentation https://docs.armbian.com/board_details/pine64/

Don't know where the repo for the website is, otherwise would have made a PR myself.

**Comment by PanderMusubi** [comment]
Related questions:

1) For maintainer on https://www.armbian.com/pine64/ you can list me

2) Also here at https://docs.armbian.com/Release_Board-Maintainers/ my username on the forum is Pander and GitHub is PanderMusubi

3) Where is the text maintained on https://www.armbian.com/pine64/ starting with `The only led on the board` ?

**Comment by igorpecovnik** [comment]
> there is a link under Documentation

You should have access to that page now. Feel free to adjust anything.

> For maintainer on https://www.armbian.com/pine64/ you can list me

You are now.

> Also here at https://docs.armbian.com/Release_Board-Maintainers/ 

This is deprecated section. Needs to be removed. Here https://www.armbian.com/authors/ is source of truth.

> Where is the text maintained on

Once you logged in, you will see edit button.
