### ISSUE TITLE
Board specifications filtering website doesn't work

### ISSUE THREAD

**Issue by PanderMusubi** [armbian/documentation#331]
On the main website, boards are tagged with labels such as `16GB`. When clicking on such a label, only boards with that label should be listed. The user expectation is that this is some sort of filtering and the URL also looks like that.

If you go to https://www.armbian.com/download/?specifications=16GB you see also boards that don't have 16 GB RAM.

(Not sure where to report website issues, hopefully here at documentation is okay. Could not find a more appropriate repo for it.)

**Comment by igorpecovnik** [comment]
Try now :)

**Comment by PanderMusubi** [comment]
Yes, works, thanks

**Comment by igorpecovnik** [comment]
Other thing is overall state of the database and troubles / improvements that would needed to be applied (nice to have) to the website. We have done a lot of fixes in past year but there are still some known bugs. As we don't have a dedicated personnel for deal with this php / wordpress, website sources should be once put on Git so anyone could fix the code, things are improving slow. A complete rework of website started mid last year then but after few months main developer had to move away ... and we only have a draft.
