### ISSUE TITLE
LIB_TAG is not supported anymore

### ISSUE THREAD

**Issue by whiler** [armbian/documentation#341]
it seems that `LIB_TAG` is not supported anymore. when i compile image with armbian/build branch v23.05, the compile.sh reports error
> LIB_TAG is set.This is not supported anymore. Please remove it, and manage the git branches manually.

**Comment by EvilOlaf** [comment]
Correct. We didn't have time to update docs yet. Feel free to send PR.

**Comment by igorpecovnik** [comment]
This was removed in recent cleaning.
