### ISSUE TITLE
IRC FAQ indentions broken

### ISSUE THREAD

**Issue by EvilOlaf** [armbian/documentation#354]
https://docs.armbian.com/Community_IRC/#faq

**Comment by littlecxm** [comment]
see
https://github.com/mkdocs/mkdocs/issues/545
https://github.com/Python-Markdown/markdown/issues/3#issuecomment-364402548

expect
<img width="1095" alt="image" src="https://github.com/armbian/documentation/assets/16154023/0263602e-005d-449c-b25f-8013923bcda0">

**Comment by EvilOlaf** [comment]
Can you provide a PR to implement this?

**Comment by littlecxm** [comment]
in last PR I've done for that, is it need rebuild current prod env to make it work?

**Comment by littlecxm** [comment]
in my test the indent looks correct at current branch 
<img width="1503" alt="image" src="https://github.com/armbian/documentation/assets/16154023/02c73099-04b4-4159-ae32-c819fa31d568">

**Comment by EvilOlaf** [comment]
Usually docs are fully rebuilt on each PR so not sure why it doesn't work. But markdown and docs gave me headaches before so...¯ \ _ (ツ) _ / ¯

**Comment by littlecxm** [comment]
did you try to install new dependencies with `pip install -r requirement.txt`? I add the the new deps on this file so maybe need re-install it

**Comment by EvilOlaf** [comment]
I don't know where docs are generated so there are updates needed.  @TheLinuxBug ?

**Comment by igorpecovnik** [comment]
on the same host as www.armbian.com ... and i already added one dependency two days ago as it was breaking the process.

**Comment by littlecxm** [comment]
<img width="1400" alt="image" src="https://github.com/armbian/documentation/assets/16154023/e3185307-d9a8-40db-9d93-b8d3af9b428a">
seems it works now?

**Comment by EvilOlaf** [comment]
Odd

`¯\_(ツ)_/¯ `
