### ISSUE TITLE
Feature request: Include testing procedures

### ISSUE THREAD

**Issue by jcstaudt** [armbian/documentation#36]
## Problem

I have noticed that one key element missing from the official Armbian documentation is formalized testing procedures.  I have personally hesitated from contributing certain reports on what **I think** are issues because I may not be testing for them in the same way as the more experienced Armbian testers and I don't want to flood the forums with ignorant concerns and reports.  I would like to enable new and upcoming contributors (like myself!) to confidently provide quality bug reports and new contributions while reducing the strain on existing developers.

## A simple example: testing a micro SD card

I own many cards that I can test on various boards.  I am able to insert any of them and have an Armbian-powered device recognize it, even if the capacity/brand of card is not officially supported on the website.  What does it mean for a card to be "supported"?  Here are a few steps I would naturally perform to determine if a functional SD card is fully compatible with the system:

1. Is the card recognized in ``lsblk``?
2. Can a file manager recognize the device? (Do I test one file manager? Several? Which ones?)
3. Can the device be mounted using a file manager?
4. Can I read existing files on the mounted SD card filesystem?
5. Can I write new files on the mounted SD card filesystem?
6. Using a N-GB card, will checksum evaluations pass if I write approximately N * 1 GB files to the card?

## Proposed steps for resolution

1. Identify if formalized test procedures are necessary
2. Discuss a test procedure and determine a clear and reproducible standard of quality for official Armbian support
3. Document the procedure and publish it within this repository

**Comment by lanefu** [comment]
@jcstaudt 

I'm sorry you feel hesitant to post on the forums.  You clearly know how to do appropriate due diligence.  I look forward to seeing more posts from you on the forums.

There is a lot that could be done to work on testing.... and a lot of different potential scopes to approach that from.    What you've provided is a great start.  Please submit a PR and hopefully it can function as inspiration for other such documentation.

**Comment by lanefu** [comment]
resolved by #38

**Comment by jgwinner** [comment]
> @lanefu
> 
> I'm sorry you feel hesitant to post on the forums. 

The ad-hominem attacks when we're trying to contribute testing data points is somewhat frustrating. This leads to a desire not to post.

**Comment by tido-** [comment]
> This leads to a desire not to post.

I read your exchange with Igor. How could you not excuse for not checking properly and wasting others time?
This tells something about you.

**Comment by jgwinner** [comment]
And so it continues.

What do you think I didn't check? I'm serious. If I screwed up, I'm more than willing to admit it.

My first line of my first post on the forum clearly said I was using the H64-B model.   Why doesn't Armbian post on the H64 page that it ONLY works with the obsolete model?

I did my homework. What exactly did I miss?

I have a non functioning board and all of this back and forth hasn't had anything substantially technical going toward solving the problem.

**Comment by tido-** [comment]
> I did my homework. What exactly did I miss?

As long as you have no problems with your eyes, simply look - does any of these boards look like yours :  https://www.armbian.com/download/?tx_maker=pine64
I answer for you: no. Yours is a totally different form factor with different HW. And with your expericence (as it states on your profile) you should least be able to guess it matters.

Igor stumbled over the fact that yours is a B (look at the vast names we have to manage), but look at your post you knew it. Now look: 
Armbian_5.88_Pineh64_Debian_stretch_dev_5.1.7.img    no B in the name. One more indicator, isn't it? But I leave it by that.

**Comment by igorpecovnik** [comment]
> What exactly did I miss?

Accepting the fact that your problem is not relevant to us?

> Igor stumbled over the fact that yours is a B

I does not matter. There is no support for Pine H6. Not for A and not for B. Support = dealing with users. There are only testing images for whatever is on that name/picture. If you have problems with those images, your messages usually goes to /dev/null  It was a miracle that it came this far. Closing again.
