### ISSUE TITLE
How to use custom scripts to build Armbain

### ISSUE THREAD

**Issue by dusikasss** [armbian/documentation#393]
I want to figure out how to use custom scripts to build Armbain.
Need help with the docker-ce.sh and ha.sh examples. 
After that I can try to add relevant information to the documentation.

**Comment by igorpecovnik** [comment]
Structure wise:
https://docs.armbian.com/Developer-Guide_Extensions/
https://docs.armbian.com/Developer-Guide_Extensions-Hooks/

Regarding HA or Docker installation specific, there, inside extensions, are 3rd party instructions. IMO we don't need to document how HA is installed, but perhaps having a list of extensions and what those extensions does.

> After that I can try to add relevant information to the documentation.

I want to bring you attention to today's [video](https://us06web.zoom.us/rec/share/FIJJFUgUZ6G3WdYS5ztTkIzBIMVqR_LtANkMoj64TaQ97CXk9a2a93DmJiMYjIPW.BMN0JhEccdy3_gsq)  on documentation.
