### ISSUE TITLE
Armbian forum contact

### ISSUE THREAD

**Issue by ilu33** [armbian/documentation#40]
I'm trying to change my email in the forum account but the confirmation link does nothing. It leads to an empty page. Login is not possible, only option is to resend the link which still doesn't do anything.
Also I can't find a help contact address neither on the forum nor on the website so I'm trying here.

**Comment by igorpecovnik** [comment]
We were forced to hide contacts as much as possible because people spam us with random technical questions all the time. sent your username to igor.pecovnik at gmail.com

**Comment by igorpecovnik** [comment]
BTW - https://www.armbian.com/#contact

**Comment by ilu33** [comment]
When I'm trying to use that contact form I'm getting the following error: 
"There was an error trying to send your message. Please try again later."

**Comment by igorpecovnik** [comment]
It should work now.
