### ISSUE TITLE
Changelog typo v25.5.1 vs correct v24.5.1

### ISSUE THREAD

**Issue by docgalaxyblock** [armbian/documentation#426]
Hello,
I just noticed that the Changelog has the wrong version listed.
https://docs.armbian.com/Release_Changelog/#v2551-2025-25-5

It should be v24.5.1 on 2024-25-5

Typo introduced in 96eda5a730c3571143d0fc55ece193b0e6fccefe.

**Comment by EvilOlaf** [comment]
ty

https://github.com/armbian/documentation/pull/427

**Comment by docgalaxyblock** [comment]
@EvilOlaf Great but you missed the date in #427
