### ISSUE TITLE
Obsolete file? lime2 emmc

### ISSUE THREAD

**Issue by heaterC** [armbian/documentation#45]
When searching armbian.com I found this file:
[https://github.com/armbian/documentation/blob/master/docs/boards/lime2-emmc.md](https://github.com/armbian/documentation/blob/master/docs/boards/lime2-emmc.md)

I tried to apply the commands, but ended at `E: Unable to locate package linux-stretch-root-next-lime2-emmc`.

Since the file is 2 years old and there's an extra image for lime2 emmc I assume that this file is obsolete?

**Comment by igorpecovnik** [comment]
That's obsolete indeed. All versions (NAND, eMMC and without) are merged under lime2
