### ISSUE TITLE
Pine64 LCD is no longer supported

### ISSUE THREAD

**Issue by technomancy** [armbian/documentation#59]
On https://docs.armbian.com/board_details/pine64/ it claims that you can use the official Pine64 7-inch LCD board by changing `/boot/armbianEnv.txt`; however this is no longer supported in recent versions: https://forum.armbian.com/topic/10434-lcd-no-longer-works-in-armbian-583-pine64/

The mention here and on https://www.armbian.com/pine64/ should probably be removed if the LCD support can't be restored.

**Comment by igorpecovnik** [comment]
Claims are fine if you use old kernel - that is perhaps not that obvious - you are welcome to fix that.

https://forum.armbian.com/topic/10434-lcd-no-longer-works-in-armbian-583-pine64/?do=findComment&comment=91232

Serge is saying he found some patches which means it could be also working on modern kernel without wasting weeks. We have no support from Pine64 so implementation and maintenance costs would be ours. The same goes for the documentation which is getting obsolete. I am aware of that, but best effort has to end somewhere.

https://docs.armbian.com/Process_Contribute/

**Comment by technomancy** [comment]
Thanks; I understand that the actual driver has to come from elsewhere.

I can submit a patch to fix the docs.armbian.com mention of the LCD
which I believe is in this repo, and if you point me to the relevant
repository I can submit one for https://www.armbian.com/pine64/; I just
don't know where that is stored.

**Comment by igorpecovnik** [comment]
> which I believe is in this repo

Yes. There is also edit button on docs.armbian.com pointing you to the correct document.

> I can submit one for https://www.armbian.com/pine64/; I just
don't know where that is stored.

This is done via custom wordpress application. Notify current @tido- 
https://forum.armbian.com/staffapplications/application/6-we-need-board-maintainers/
If no response or if you want to do it yourself ... I have to give you access tied to your email.

The best would be to find and add kernel patches - which I do believe they exists. Build kernel with them - our tool help you in this - and after you got display working, send them here https://github.com/armbian/build/tree/master/patch/kernel
