### ISSUE TITLE
Strip out remaining HTML and metacharacters

### ISSUE THREAD

**Issue by lanefu** [armbian/documentation#63]
Some of the markdown docs have old HTML formatting in them... if someone could pull the htML and special characters and replace with markdown.. that would be *WONDERFUL*.  

sometimes they can be difficult to edit.

**Comment by EvilOlaf** [comment]
Is this still an issue? Quite a while ago I made an overhaul of most documents and stripped HTML I could find.

**Comment by lanefu** [comment]
Looks good to me.. thank you!

```
lane@hambone:~/GIT/ARMBIAN/documentation/docs$ fgrep '<p>' *
Release_Changelog.md:<p>
Release_Changelog.md:Closed tasks<p>
lane@hambone:~/GIT/ARMBIAN/documentation/docs$ fgrep '<a href>' *
lane@hambone:~/GIT/ARMBIAN/documentation/docs$ fgrep '<b>' *
lane@hambone:~/GIT/ARMBIAN/documentation/docs$
```
