### ISSUE TITLE
Add quickstart guide for new users

### ISSUE THREAD

**Issue by lanefu** [armbian/documentation#94]
A lot of the documentation is all over there place.

Maybe a simple quickstart guide, that just quickly goes through the steps of imaging, logging in, setting locales, and running armbian-config to configure hostname etc.

**Comment by lanefu** [comment]
I guess Getting Started section covers this, but still kind of wonder if we need something simplifer

**Comment by EvilOlaf** [comment]
Maybe... well some mentioned stuff could be put more detailed under `Getting started` (if not covered somewhere else in the docs) and then stripped down again for a quick start....

**Comment by igorpecovnik** [comment]
What about short video?

**Comment by EvilOlaf** [comment]
> 
> 
> What about short video?

If so what should it cover?
- Select proper image for board
- - Add hint how to get constellations that are not provided offically -> mention build script
- Writing to sd card using USBimager or Etcher as fallback
- First boot until welcome screen
- Do initial setup with password
- Show `armbian-config`
- - Maybe mention that everything the tool can can be done manually too
- Show how to provide logs the proper way: `armbianmonitor -u `

**Comment by EvilOlaf** [comment]
I started writing a script for an actual video to cover the basic steps. I will put a link here once it is ready for review.

**Comment by EvilOlaf** [comment]
https://docs.google.com/document/d/1eEEecUXF-o8pQ4MyU29qm0NTNVT7XnTOzw8x30rboEo/edit?usp=sharing

**Comment by NicoD-SBC** [comment]
Hi guys. I had filmed a video this afternoon after filming a part for the RockPiX. 
I didn't think of looking here, Igor had told me about it. But my brain is cold tomato soup...
I'll make a few other quick ones too. Already made one about building an image, and also one about installing on the RockPi4. 
Cheers.

**Comment by EvilOlaf** [comment]
Done

https://www.youtube.com/watch?v=hFrdyLc4g50
This is awesome @NicoD-SBC
