### ISSUE TITLE
Remove Bananian Conversion from Documentation

### ISSUE THREAD

**Issue by lanefu** [armbian/documentation#95]
This is no longer relevant correct?

https://docs.armbian.com/User-Guide_Migration_from_Bananian/

can I remove that section? @igorpecovnik

**Comment by EvilOlaf** [comment]
Perhaps not remove yet but mark as deprecated for removal somewhen in future?

**Comment by igorpecovnik** [comment]
Or perhaps just remove from main index?

**Comment by lanefu** [comment]
Did both. thanks

https://github.com/armbian/documentation/commit/cd38db0fbe9a125b9942d2872dda87adddda6f7b
