### ISSUE TITLE
Automatic pdf output...

### ISSUE THREAD

**Issue by EvilOlaf** [armbian/documentation#96]
... as already been played around with Github actions and proofen to work 😛 
@lanefu

**Comment by EvilOlaf** [comment]
Now we have to decide where and how to push the pdf.

**Comment by EvilOlaf** [comment]
It seems it is now possible to get a link via API to the artifact: https://developer.github.com/v3/actions/artifacts/
Also interesting: https://github.com/oprypin/nightly.link

https://nightly.link/armbian/documentation/workflows/recreate_on_push.yaml/master/artifact.zip should lead always to the latest artifact.

**Comment by TRSx80** [comment]
This is all very neat and everything, but are we actually using the generated PDFs for anything?

I have not played with Docs in some time, but I seem to recall that commenting out `- with-pdf:` line in [mkdocs.yml](https://github.com/armbian/documentation/blob/master/mkdocs.yml) cut my local rendering time down from minutes to seconds.  Which helps a lot while editing docs locally, before pushing changes back up.

And if we are not using them for anything (yet) maybe we should comment this out by default until we are?

**Comment by EvilOlaf** [comment]
Sure,  go ahead. I don't think it is used atm.

**Comment by TRSx80** [comment]
OK cool, thanks.  I am sending a few more touch ups on Board Maintainers, then will start on other things.

**Comment by TRSx80** [comment]
OK, commented out in #176.

Do we still want to keep this open?  I dunno what you had/have in mind here.

**Comment by igorpecovnik** [comment]
Now action is failing - has to be disabled and badge in readme file.
https://github.com/armbian/documentation/actions/runs/1778956948

**Comment by TRSx80** [comment]
Yeah, I had just noticed that, too, and commented in IRC.  Looking into it already.

**Comment by igorpecovnik** [comment]
Just leave as is. We don't use PDF and if needed in the future, we will give this back.

**Comment by TRSx80** [comment]
I dunno, I was all gung-ho to remove it, now thinking why not leave it?  Maybe some people use it?  But I have no idea, so I started a [thread](https://forum.armbian.com/topic/19778-anyone-using-pdf-documentation) on the forums.  I guess it doesn't hurt to leave it?

**Comment by igorpecovnik** [comment]
>  I guess it doesn't hurt to leave it?

There is no damage if we have it since its an automated job.

**Comment by TRSx80** [comment]
OK I will work on putting everything back how it was.  Probably after dinner.

**Comment by igorpecovnik** [comment]
actions are enabled back

**Comment by TRSx80** [comment]
You just want to revert back to 9ce3e73?  That would revert my breaking change, and put back the badge.  Basically back to where we were.  I don't know how to do that in GitHub though (only on command line), or if I even have permission to do so.

**Comment by igorpecovnik** [comment]
Done in CLI. I also don't know how to do it on Github.
